service: neurotrackerapi
frameworkVersion: "2"

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    NeuroTrackerRDSSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: "RDS DB Credentials"
        Description: "Credentials for Neuro Tracker DB"
        GenerateSecretString: '{"username": "master"}'
        PasswordLength: 32
        ExcludeCharacters: '"@/\"'

    NeuroTrackerDataAPIDearLife:
      Type: AWS::SecretsManager::SecretTargetAttachment
      Properties:
        SecretId: !Ref NeuroTrackerRDSSecret
        TargetId: !Ref NeuroTrackerRDS
        TargetType: AWS::RDS::DBCluster

    NeuroTrackerRDS:
      Type: AWS::RDS::DBCluster,
      DatabaseName: "neurotrackerdb"
      EnableHttpEndpoint: true,
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: "5.7.12"
      MasterUsername: !Sub "{{resolve:secretsmanager:${NeuroTrackerRDSSecret}::username}}"
      MasterUserNamePassword: !Sub "{{resolve:secretsmanager:${NeuroTrackerRDSSecret}::username}}"
