name: backend-deploy
on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"
      - ".github"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - run: npm install serverless
        working-directory: ./backend
      - run: npm run deploy
        working-directory: ./backend
